from __future__ import annotations

# Standard library imports
from typing import Dict, List, Any, Optional, Union, Literal, TypedDict
import logging
from pathlib import Path
import os

# Third-party imports
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import HumanMessage, BaseMessage
from langchain_core.documents import Document
from pydantic import BaseModel, Field
from langchain_core.runnables.graph import CurveStyle, MermaidDrawMethod, NodeStyles

# Local imports
from storybook.agents.character_developer import CharacterDeveloper
from storybook.agents.dialogue_enhancer import DialogueEnhancer
from storybook.agents.world_builder import WorldBuilder
from storybook.agents.subplot_weaver import SubplotWeaver
from storybook.agents.story_arc_analyst import StoryArcAnalyst
from storybook.agents.continuity_editor import ContinuityEditor
from storybook.agents.language_polisher import LanguagePolisher
from storybook.agents.quality_reviewer import QualityReviewer
from storybook.agents.market_researcher import MarketResearcher
from storybook.agents.content_analyzer import ContentAnalyzer
from storybook.db.document_store import DocumentStore

logger = logging.getLogger(__name__)


class StorybookState(TypedDict):
    """State definition for the Storybook workflow."""
    # Input fields (required at start)
    manuscript: str  # Required: The raw manuscript text
    title: str  # Required: The manuscript title
    synopsis: str  # Required: Brief synopsis of the work

    # Project management fields (owned by supervisor)
    manuscript_id: Optional[str]  # Generated by supervisor after intake
    status: Optional[str]  # Current workflow status
    current_team: Optional[str]  # Current active team
    stage_progress: Optional[Dict[str, float]]  # Progress tracking

    # Research team outputs
    target_audience: Optional[Dict[str, Any]]  # Set by market research
    research_insights: Optional[Dict[str, Any]]  # Market and genre research
    analysis_results: Optional[Dict[str, Any]]  # Content analysis results

    # Writing team outputs
    settings: Optional[List[Dict[str, Any]]]  # World building results
    characters: Optional[List[Dict[str, Any]]]  # Character development
    subplots: Optional[List[Dict[str, Any]]]  # Subplot integration
    draft_version: Optional[int]  # Current draft number
    
    # Editorial team outputs
    story_analysis: Optional[Dict[str, Any]]  # Story arc evaluation
    continuity_issues: Optional[List[Dict[str, Any]]]  # Continuity checks
    style_analysis: Optional[Dict[str, Any]]  # Language polish results
    final_review: Optional[Dict[str, Any]]  # Quality review results

    # Team status tracking
    research_status: Optional[Dict[str, bool]]  # Research team progress
    writing_status: Optional[Dict[str, bool]]  # Writing team progress
    editorial_status: Optional[Dict[str, bool]]  # Editorial team progress


def start_workflow(state: Dict[str, Any]) -> Dict[str, Any]:
    """Start the workflow with a new manuscript."""
    logger.info("Starting workflow")

    # Validate required input fields
    required_fields = ["manuscript", "title", "synopsis"]
    missing_fields = [f for f in required_fields if not state.get(f)]
    if missing_fields:
        return {
            "status": "error",
            "message": f"Error: {', '.join(missing_fields)} required to start the process."
        }

    # Initialize document store
    document_store = DocumentStore()
    
    # Organize manuscript data
    manuscript_data = {
        "content": state["manuscript"],
        "title": state["title"],
        "synopsis": state["synopsis"],
        "metadata": {
            "created_at": datetime.now().isoformat(),
            "word_count": len(state["manuscript"].split()),
        }
    }
    
    # Store manuscript and get ID
    manuscript_id = document_store.store_manuscript(manuscript_data)

    # Initialize state with only required starting fields
    return {
        "manuscript": state["manuscript"],
        "title": state["title"],
        "synopsis": state["synopsis"],
        "manuscript_id": manuscript_id,
        "status": "started",
        "current_team": "research",
        "stage_progress": {"intake": 1.0},
        # Initialize optional fields as None
        "target_audience": None,
        "research_insights": None,
        "analysis_results": None,
        "settings": None,
        "characters": None,
        "subplots": None,
        "draft_version": 0,
        "story_analysis": None,
        "continuity_issues": None,
        "style_analysis": None,
        "final_review": None,
        # Initialize team status tracking
        "research_status": {
            "market_research": False,
            "content_analysis": False,
            "audience_analysis": False
        },
        "writing_status": {
            "world_building": False,
            "character_development": False,
            "draft": False
        },
        "editorial_status": {
            "review": False,
            "polish": False,
            "quality": False
        }
    }


def conduct_market_research(state: Dict[str, Any]) -> Dict[str, Any]:
    """Conduct market research on publishing trends and target audience."""
    logger.info(f"Conducting market research for manuscript {state['manuscript_id']}")

    agent = MarketResearcher()
    result = agent.research_market(state["manuscript_id"], state["title"])

    # Update state with research insights
    new_state = state.copy()
    new_state["research_insights"] = result.get("research_insights", {})
    new_state["target_audience"] = result.get("target_audience", {})
    new_state["current_state"] = "analysis"
    new_state["message"] = (
        "Completed market research on publishing trends and target audience."
    )
    new_state["stage_progress"] = {**state.get("stage_progress", {}), "research": 1.0}

    # Store the research insights in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result.get("research_insights", {})),
        metadata={
            "type": "market_research",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("research", [doc])

    return new_state


def analyze_manuscript(state: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze manuscript content using NLP techniques."""
    logger.info(f"Analyzing manuscript {state['manuscript_id']}")

    agent = ContentAnalyzer()
    result = agent.analyze_content(state["manuscript_id"])

    # Update state with analysis results
    new_state = state.copy()
    new_state["analysis_results"] = result.get("analysis", {})
    new_state["current_state"] = "initialize"
    new_state["message"] = "Completed NLP analysis of manuscript content."
    new_state["stage_progress"] = {**state.get("stage_progress", {}), "analysis": 1.0}

    # Store the analysis results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result.get("analysis", {})),
        metadata={
            "type": "content_analysis",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def initialize_graph(state: Dict[str, Any]) -> Dict[str, Any]:
    """Initialize the graph with a new manuscript."""
    logger.info("Initializing graph")

    # At this point, we already have research and analysis
    # Update state to move to next phase
    new_state = state.copy()
    new_state["current_state"] = "character_development"
    new_state["message"] = (
        f"Research and analysis complete. Starting character development for {state['title']}."
    )
    new_state["stage_progress"] = {**state.get("stage_progress", {}), "initialize": 1.0}

    return new_state


def develop_characters(state: Dict[str, Any]) -> Dict[str, Any]:
    """Develop and enhance characters in the manuscript."""
    logger.info(f"Developing characters for manuscript {state['manuscript_id']}")

    agent = CharacterDeveloper()
    result = agent.enhance_characters(
        state["manuscript_id"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state with character information
    new_state = state.copy()
    new_state["characters"] = result.get("characters", [])
    new_state["current_state"] = "dialogue_enhancement"
    new_state["message"] = (
        f"Enhanced {len(new_state['characters'])} characters based on target audience research."
    )
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "character_development": 1.0,
    }

    # Store the character development results in MongoDB Atlas Vector
    document_store = DocumentStore()
    for character in result.get("characters", []):
        doc = Document(
            page_content=str(character),
            metadata={
                "type": "character_development",
                "character_name": character.get("name", "Unknown"),
                "manuscript_id": state["manuscript_id"],
                "title": state["title"],
            },
        )
        document_store.db.store_documents_with_embeddings("characters", [doc])

    return new_state


def enhance_dialogue(state: Dict[str, Any]) -> Dict[str, Any]:
    """Enhance dialogue in the manuscript."""
    logger.info(f"Enhancing dialogue for manuscript {state['manuscript_id']}")

    agent = DialogueEnhancer()
    result = agent.enhance_dialogue(
        state["manuscript_id"],
        state["characters"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["current_state"] = "world_building"
    new_state["message"] = result.get("message", "Dialogue enhancement completed.")
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "dialogue_enhancement": 1.0,
    }

    # Store the dialogue enhancement results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result),
        metadata={
            "type": "dialogue_enhancement",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def build_world(state: Dict[str, Any]) -> Dict[str, Any]:
    """Build and enhance the world and settings."""
    logger.info(f"Building world for manuscript {state['manuscript_id']}")

    agent = WorldBuilder()
    result = agent.build_world(
        state["manuscript_id"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["settings"] = result.get("settings", [])
    new_state["current_state"] = "subplot_integration"
    new_state["message"] = (
        f"Enhanced {len(new_state['settings'])} settings based on research."
    )
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "world_building": 1.0,
    }

    # Store the world building results in MongoDB Atlas Vector
    document_store = DocumentStore()
    for setting in result.get("settings", []):
        doc = Document(
            page_content=str(setting),
            metadata={
                "type": "world_building",
                "setting_name": setting.get("name", "Unknown"),
                "manuscript_id": state["manuscript_id"],
                "title": state["title"],
            },
        )
        document_store.db.store_documents_with_embeddings("worlds", [doc])

    return new_state


def integrate_subplots(state: Dict[str, Any]) -> Dict[str, Any]:
    """Integrate subplots into the manuscript."""
    logger.info(f"Integrating subplots for manuscript {state['manuscript_id']}")

    agent = SubplotWeaver()
    result = agent.weave_subplots(
        state["manuscript_id"],
        state["characters"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["subplots"] = result.get("developed_subplots", [])
    new_state["current_state"] = "story_arc_evaluation"
    new_state["message"] = result.get("message", "Subplot integration completed.")
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "subplot_integration": 1.0,
    }

    # Store the subplot integration results in MongoDB Atlas Vector
    document_store = DocumentStore()
    for subplot in result.get("developed_subplots", []):
        doc = Document(
            page_content=str(subplot),
            metadata={
                "type": "subplot_integration",
                "subplot_title": subplot.get("title", "Unknown"),
                "manuscript_id": state["manuscript_id"],
                "title": state["title"],
            },
        )
        document_store.db.store_documents_with_embeddings("subplots", [doc])

    return new_state


def evaluate_story_arcs(state: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze and refine story arcs."""
    logger.info(f"Evaluating story arcs for manuscript {state['manuscript_id']}")

    agent = StoryArcAnalyst()
    result = agent.refine_story_arcs(
        state["manuscript_id"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["story_analysis"] = result.get("analysis", {})
    new_state["current_state"] = "continuity_check"
    new_state["message"] = result.get(
        "message", "Story arc analysis and refinement completed."
    )
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "story_arc_evaluation": 1.0,
    }

    # Update the analysis results with progress tracking
    analysis_agent = ContentAnalyzer()
    progress_analysis = analysis_agent.analyze_progress(
        state["manuscript_id"], state.get("analysis_results", {}), "story_arc"
    )
    new_state["analysis_results"] = {
        **new_state.get("analysis_results", {}),
        **progress_analysis,
    }

    # Store the story arc analysis results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result.get("analysis", {})),
        metadata={
            "type": "story_arc_evaluation",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    # Also store the progress analysis
    doc = Document(
        page_content=str(progress_analysis),
        metadata={
            "type": "progress_analysis",
            "stage": "story_arc",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def check_continuity(state: Dict[str, Any]) -> Dict[str, Any]:
    """Check and fix continuity issues."""
    logger.info(f"Checking continuity for manuscript {state['manuscript_id']}")

    agent = ContinuityEditor()
    result = agent.check_and_fix_continuity(state["manuscript_id"])

    # Update state
    new_state = state.copy()
    new_state["continuity_issues"] = result.get("issues", [])
    new_state["current_state"] = "language_polishing"
    new_state["message"] = result.get("message", "Continuity check completed.")
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "continuity_check": 1.0,
    }

    # Store the continuity check results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result),
        metadata={
            "type": "continuity_check",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
            "issues_fixed": len(result.get("issues", [])),
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def polish_language(state: Dict[str, Any]) -> Dict[str, Any]:
    """Polish language and style."""
    logger.info(f"Polishing language for manuscript {state['manuscript_id']}")

    agent = LanguagePolisher()
    result = agent.polish_language(
        state["manuscript_id"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["style_analysis"] = result.get("style_analysis", {})
    new_state["current_state"] = "quality_review"
    new_state["message"] = result.get("message", "Language polishing completed.")
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "language_polishing": 1.0,
    }

    # Update the analysis results with progress tracking
    analysis_agent = ContentAnalyzer()
    progress_analysis = analysis_agent.analyze_progress(
        state["manuscript_id"], state.get("analysis_results", {}), "language"
    )
    new_state["analysis_results"] = {
        **new_state.get("analysis_results", {}),
        **progress_analysis,
    }

    # Store the language polishing results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result),
        metadata={
            "type": "language_polishing",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    # Also store the progress analysis
    doc = Document(
        page_content=str(progress_analysis),
        metadata={
            "type": "progress_analysis",
            "stage": "language",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def review_quality(state: Dict[str, Any]) -> Dict[str, Any]:
    """Perform final quality review."""
    logger.info(f"Reviewing quality for manuscript {state['manuscript_id']}")

    agent = QualityReviewer()
    result = agent.finalize_manuscript(
        state["manuscript_id"],
        target_audience=state.get("target_audience", {}),
        research_insights=state.get("research_insights", {}),
    )

    # Update state
    new_state = state.copy()
    new_state["final_review"] = {
        "review": result.get("review", ""),
        "improvements": result.get("improvements", []),
        "final_report": result.get("final_report", ""),
    }
    new_state["current_state"] = "finalize"
    new_state["message"] = result.get("message", "Quality review completed.")
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "quality_review": 1.0,
    }

    # Final analysis to evaluate overall improvements
    analysis_agent = ContentAnalyzer()
    final_analysis = analysis_agent.analyze_progress(
        state["manuscript_id"], state.get("analysis_results", {}), "complete"
    )
    new_state["analysis_results"] = {
        **new_state.get("analysis_results", {}),
        **final_analysis,
    }

    # Store the quality review results in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=result.get("final_report", ""),
        metadata={
            "type": "quality_review",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    # Also store the final analysis
    doc = Document(
        page_content=str(final_analysis),
        metadata={
            "type": "progress_analysis",
            "stage": "complete",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def finalize(state: Dict[str, Any]) -> Dict[str, Any]:
    """Finalize the transformation process."""
    logger.info(f"Finalizing transformation for manuscript {state['manuscript_id']}")

    # Create a summary of the transformation process
    manuscript_id = state["manuscript_id"]
    document_store = DocumentStore()
    manuscript = document_store.get_manuscript(manuscript_id)

    # Prepare final state
    new_state = state.copy()
    new_state["current_state"] = END
    new_state["message"] = (
        f"Transformation complete for manuscript: {state.get('title', 'Untitled')}. "
        f"Enhanced {len(state['characters'])} characters, {len(state['settings'])} settings, "
        f"and integrated {len(state['subplots'])} subplots. "
        f"Fixed {len(state['continuity_issues'])} continuity issues. "
        f"Final report available in the final_review field."
    )
    new_state["stage_progress"] = {**state.get("stage_progress", {}), "finalize": 1.0}

    # Create a final summary document and store it in MongoDB Atlas Vector
    final_report = state.get("final_review", {}).get("final_report", "")

    improvement_metrics = {
        "characters_enhanced": len(state.get("characters", [])),
        "settings_developed": len(state.get("settings", [])),
        "subplots_integrated": len(state.get("subplots", [])),
        "continuity_issues_fixed": len(state.get("continuity_issues", [])),
        "language_improvements": state.get("style_analysis", {}).get(
            "improvements_count", 0
        ),
    }

    # Store the comprehensive final report in MongoDB Atlas Vector
    doc = Document(
        page_content=final_report,
        metadata={
            "type": "final_report",
            "manuscript_id": manuscript_id,
            "title": state.get("title", "Untitled"),
            "improvement_metrics": str(improvement_metrics),
            "completion_status": "complete",
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    # Create the output
    return {
        "manuscript_id": manuscript_id,
        "status": "complete",
        "final_report": final_report,
        "research_insights": state.get("research_insights", {}),
        "analysis_results": state.get("analysis_results", {}),
        "improvement_metrics": improvement_metrics,
    }


def should_retry_character_development(state: Dict[str, Any]) -> str:
    """Determine if character development needs to be retried."""
    if not state.get("characters"):
        return "character_development"
    return "dialogue_enhancement"


def route_after_quality_review(state: Dict[str, Any]) -> str:
    """Route after quality review depending on final review content."""
    # If there's a comprehensive final review, proceed to finalize
    if state.get("final_review") and "review" in state["final_review"]:
        return "finalize"
    # Otherwise retry quality review
    return "quality_review"


def check_analysis_progress(
    state: Dict[str, Any],
) -> Union[Literal["initialize"], Literal["analysis"]]:
    """Check if the analysis is complete and comprehensive enough."""
    analysis_results = state.get("analysis_results", {})

    # Check if we have comprehensive analysis data
    required_analysis_types = [
        "sentiment",
        "readability",
        "content_structure",
        "genre_match",
    ]

    for analysis_type in required_analysis_types:
        if (analysis_type not in analysis_results) or (not analysis_results[analysis_type]):
            return "analysis"  # Retry analysis

    # If all required data is present, move to initialization
    return "initialize"


def manage_project(state: Dict[str, Any]) -> Dict[str, Any]:
    """Project Supervisor: Oversee entire manuscript transformation process."""
    new_state = state.copy()
    new_state["project_status"] = {
        "phase": "research" if not state.get("research_complete") else "writing",
        "progress": state.get("stage_progress", {}),
        "current_team": "research" if not state.get("research_complete") else "writing"
    }
    return new_state

def manage_research(state: Dict[str, Any]) -> Dict[str, Any]:
    """Research Supervisor: Manage market research and analysis teams."""
    new_state = state.copy()
    new_state["research_status"] = {
        "market_research_complete": state.get("research_insights") is not None,
        "content_analysis_complete": state.get("analysis_results") is not None,
        "audience_analysis_complete": state.get("target_audience") is not None
    }
    return new_state

def manage_writing(state: Dict[str, Any]) -> Dict[str, Any]:
    """Writing Supervisor: Manage creative writing and development teams."""
    new_state = state.copy()
    new_state["writing_status"] = {
        "world_building_complete": len(state.get("settings", [])) > 0,
        "character_development_complete": len(state.get("characters", [])) > 0,
        "subplot_integration_complete": len(state.get("subplots", [])) > 0,
        "dialogue_enhancement_complete": state.get("dialogue_enhanced", False),
        "draft_complete": state.get("draft_version", 0) > 0
    }
    return new_state

def manage_editorial(state: Dict[str, Any]) -> Dict[str, Any]:
    """Editorial Supervisor: Manage quality control and review teams."""
    new_state = state.copy()
    new_state["editorial_status"] = {
        "story_arc_reviewed": state.get("story_analysis") is not None,
        "continuity_checked": state.get("continuity_issues") is not None,
        "language_polished": state.get("style_analysis") is not None,
        "quality_reviewed": state.get("final_review") is not None
    }
    return new_state


def research_complete_check(state: Dict[str, Any]) -> str:
    """Check if research phase is complete and route accordingly."""
    research_status = state.get("research_status", {})
    
    # Check if all research tasks are complete
    if all([
        research_status.get("market_research_complete", False),
        research_status.get("content_analysis_complete", False),
        research_status.get("audience_analysis_complete", False)
    ]):
        return "project_supervisor"  # Report completion
    
    # If not started, begin with market research
    if not research_status:
        return "market_research"
        
    # Continue with next research task
    if not research_status.get("market_research_complete"):
        return "market_research"
    if not research_status.get("content_analysis_complete"):
        return "content_analysis"
    return "audience_analysis"

def start_writing_check(state: Dict[str, Any]) -> str:
    """Determine whether to start writing or move to editorial."""
    project_status = state.get("project_status", {})
    
    if project_status.get("phase") == "writing":
        return "writing_supervisor"
    if project_status.get("phase") == "editorial":
        return "editorial_supervisor"
    return "writing_supervisor"  # Default to writing phase

def assign_writing_task(state: Dict[str, Any]) -> str:
    """Assign next writing task based on completion status."""
    writing_status = state.get("writing_status", {})
    
    # Check completion status
    if writing_status.get("world_building_complete", False) and \
       writing_status.get("character_development_complete", False) and \
       writing_status.get("subplot_integration_complete", False) and \
       writing_status.get("dialogue_enhancement_complete", False) and \
       writing_status.get("draft_complete", False):
        return "project_supervisor"  # All tasks complete
    
    # Assign tasks in sequence
    if not writing_status.get("world_building_complete"):
        return "world_building"
    if not writing_status.get("character_development_complete"):
        return "character_development"
    if not writing_status.get("subplot_integration_complete"):
        return "subplot_integration"
    if not writing_status.get("dialogue_enhancement_complete"):
        return "dialogue_enhancement"
    return "draft_writing"

def assign_editorial_task(state: Dict[str, Any]) -> str:
    """Assign next editorial task based on completion status."""
    editorial_status = state.get("editorial_status", {})
    
    # Check if all editorial tasks are complete
    if all([
        editorial_status.get("story_arc_reviewed", False),
        editorial_status.get("continuity_checked", False),
        editorial_status.get("language_polished", False),
        editorial_status.get("quality_reviewed", False)
    ]):
        return "project_supervisor"  # Report completion
    
    # Assign tasks in sequence
    if not editorial_status.get("story_arc_reviewed"):
        return "story_arc_evaluation"
    if not editorial_status.get("continuity_checked"):
        return "continuity_check"
    if not editorial_status.get("language_polished"):
        return "language_polishing"
    return "quality_review"

def final_quality_check(state: Dict[str, Any]) -> str:
    """Determine if manuscript needs revisions or can be finalized."""
    final_review = state.get("final_review", {})
    quality_score = final_review.get("quality_score", 0)
    
    if quality_score >= 0.9:
        return "finalize"
    return "writing_supervisor"  # Return for revisions


def analyze_audience(state: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze and refine target audience information."""
    logger.info(f"Analyzing target audience for manuscript {state['manuscript_id']}")

    agent = ContentAnalyzer()
    result = agent.analyze_audience(
        state["manuscript_id"],
        research_insights=state.get("research_insights", {}),
        analysis_results=state.get("analysis_results", {})
    )

    # Update state with audience analysis
    new_state = state.copy()
    new_state["target_audience"] = result.get("target_audience", {})
    new_state["current_state"] = "research_supervisor"
    new_state["message"] = "Completed target audience analysis."
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "audience_analysis": 1.0
    }

    # Store the audience analysis in MongoDB Atlas Vector
    document_store = DocumentStore()
    doc = Document(
        page_content=str(result.get("target_audience", {})),
        metadata={
            "type": "audience_analysis",
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("analysis", [doc])

    return new_state


def write_draft(state: Dict[str, Any]) -> Dict[str, Any]:
    """Write or revise manuscript draft based on research and development."""
    logger.info(f"Writing/revising draft for manuscript {state['manuscript_id']}")

    # Initialize new state
    new_state = state.copy()
    current_version = state.get("draft_version", 0)
    new_state["draft_version"] = current_version + 1

    # Gather all development materials
    writing_materials = {
        "world_building": state.get("settings", []),
        "characters": state.get("characters", []),
        "subplots": state.get("subplots", []),
        "target_audience": state.get("target_audience", {}),
        "research_insights": state.get("research_insights", {}),
        "story_analysis": state.get("story_analysis", {}),
    }

    # Store the draft and development materials in MongoDB Atlas Vector
    document_store = DocumentStore()
    
    # Store the current draft version
    doc = Document(
        page_content=str(writing_materials),
        metadata={
            "type": "draft",
            "version": new_state["draft_version"],
            "manuscript_id": state["manuscript_id"],
            "title": state["title"],
        },
    )
    document_store.db.store_documents_with_embeddings("drafts", [doc])

    # Update state
    new_state["current_state"] = "writing_supervisor"
    new_state["message"] = f"Completed draft version {new_state['draft_version']}"
    new_state["stage_progress"] = {
        **state.get("stage_progress", {}),
        "draft_writing": min(1.0, (current_version + 1) / 5),  # Assume max 5 drafts
    }

    # Track draft completion
    new_state["writing_status"] = {
        **state.get("writing_status", {}),
        "draft_complete": True,
        "current_draft": new_state["draft_version"]
    }

    return new_state


def build_storybook() -> StateGraph:
    """Build the storybook workflow graph with team-based structure."""
    workflow = StateGraph(StorybookState)

    # Add supervisor nodes
    workflow.add_node("project_supervisor", manage_project)
    workflow.add_node("research_supervisor", manage_research)
    workflow.add_node("writing_supervisor", manage_writing)
    workflow.add_node("editorial_supervisor", manage_editorial)

    # Research Team Nodes
    workflow.add_node("market_research", conduct_market_research)
    workflow.add_node("content_analysis", analyze_manuscript)
    workflow.add_node("audience_analysis", analyze_audience)

    # Writing Team Nodes
    workflow.add_node("world_building", build_world)
    workflow.add_node("character_development", develop_characters)
    workflow.add_node("subplot_integration", integrate_subplots)
    workflow.add_node("dialogue_enhancement", enhance_dialogue)
    workflow.add_node("draft_writing", write_draft)

    # Editorial Team Nodes
    workflow.add_node("story_arc_evaluation", evaluate_story_arcs)
    workflow.add_node("continuity_check", check_continuity)
    workflow.add_node("language_polishing", polish_language)
    workflow.add_node("quality_review", review_quality)
    workflow.add_node("finalize", finalize)

    # Set entry point to project supervisor
    workflow.set_entry_point("project_supervisor")
    
    # Define supervisor hierarchy
    workflow.add_edge("project_supervisor", "research_supervisor")
    workflow.add_conditional_edges(
        "research_supervisor",
        research_complete_check,
        {
            "project_supervisor": "project_supervisor",  # Report back to supervisor
            "market_research": "market_research"  # Start research if needed
        }
    )
    
    # Research Team Workflow
    workflow.add_edge("market_research", "content_analysis")
    workflow.add_edge("content_analysis", "audience_analysis")
    workflow.add_edge("audience_analysis", "research_supervisor")  # Report back
    
    # Writing Team Workflow
    workflow.add_conditional_edges(
        "project_supervisor",
        start_writing_check,
        {
            "writing_supervisor": "writing_supervisor",
            "editorial_supervisor": "editorial_supervisor"
        }
    )
    
    # Writing Team Internal Workflow
    workflow.add_conditional_edges(
        "writing_supervisor",
        assign_writing_task,
        {
            "world_building": "world_building",
            "character_development": "character_development",
            "subplot_integration": "subplot_integration",
            "dialogue_enhancement": "dialogue_enhancement",
            "draft_writing": "draft_writing",
            "project_supervisor": "project_supervisor"  # Report completion
        }
    )
    
    # Editorial Team Workflow
    workflow.add_conditional_edges(
        "editorial_supervisor",
        assign_editorial_task,
        {
            "story_arc_evaluation": "story_arc_evaluation",
            "continuity_check": "continuity_check",
            "language_polishing": "language_polishing",
            "quality_review": "quality_review",
            "project_supervisor": "project_supervisor"  # Report completion
        }
    )
    
    # Final Quality Gate
    workflow.add_conditional_edges(
        "project_supervisor",
        final_quality_check,
        {
            "writing_supervisor": "writing_supervisor",  # Return for revisions
            "finalize": "finalize"  # Proceed to completion
        }
    )
    
    workflow.add_edge("finalize", END)

    return workflow

# Create the compiled graph
storybook = build_storybook().compile()

# Generate and save graph visualization
def save_graph_visualization(output_path: str = "graph.png") -> None:
    """Generate and save a visualization of the storybook workflow graph."""
    try:
        # Create custom node styles
        node_styles = NodeStyles(
            supervisor={"fill": "#c4a7e7", "stroke": "#6e6a86"},
            research={"fill": "#ebbcba", "stroke": "#6e6a86"},
            writing={"fill": "#9ccfd8", "stroke": "#6e6a86"},
            editorial={"fill": "#f6c177", "stroke": "#6e6a86"}
        )

        # Generate the PNG
        png_data = storybook.get_graph().draw_mermaid_png(
            draw_method=MermaidDrawMethod.API,
            curve_style=CurveStyle.CURVED,
            node_styles=node_styles
        )

        # Ensure output directory exists
        output_dir = os.path.dirname(os.path.abspath(output_path))
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        # Save the PNG
        with open(output_path, "wb") as f:
            f.write(png_data)
        
        logger.info(f"Graph visualization saved to {output_path}")
    except Exception as e:
        logger.error(f"Failed to generate graph visualization: {e}")

# Generate visualization when module is run directly
if __name__ == "__main__":
    save_graph_visualization("docs/storybook_graph.png")
